export const ADD_NODE = 'REDUX_PROP_GRAPH_ADD_NODE';
export const ADD_EDGE = 'REDUX_PROP_GRAPH_ADD_EDGE';
export const REMOVE_NODE = 'REDUX_PROP_GRAPH_REMOVE_NODE';
export const UNLINK_NODE = 'REDUX_PROP_GRAPH_UNLINK_NODE';
export const UNLINK_TWO = 'REDUX_PROP_GRAPH_UNLINK_TWO';